version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aqeel
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: my_database
    volumes:
      # - my_pg_data:/var/lib/postgresql/data
      - ./my_local_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my-redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./my_local_redis_data:/data

volumes:
  # my_pg_data:
  my_local_pg_data:
  my_local_redis_data:

